### ISSUE TITLE
add access control

### ISSUE THREAD

**Issue by schmunk42** [ignatenkovnikita/yii2-queuemanager#2]
Currently you can access the job list and real-time stats without being logged in.
Would be good to have some kind of access control here.

**Comment by ignatenkovnikita** [comment]
Currently need access control) If you fix problem, big thanks)

**Comment by schmunk42** [comment]
Here you go :)

It would also be great if you could tag a release, eg. `0.1.0` or `0.1.0-beta1`.

**Comment by ignatenkovnikita** [comment]
all right?)
