### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by schmunk42** [ignatenkovnikita/yii2-queuemanager#4]
eg. `0.1.0` or `0.1.0-beta1` - see also https://github.com/ignatenkovnikita/yii2-queuemanager/issues/2#issuecomment-398403754

**Comment by schmunk42** [comment]
Ping :wave::smile:

**Comment by ignatenkovnikita** [comment]
Add release ) https://github.com/ignatenkovnikita/yii2-queuemanager/releases/tag/v0.1.0

**Comment by ignatenkovnikita** [comment]
all right?)

**Comment by schmunk42** [comment]
Perfect, thank you very much!
